# Generated by Django 3.2.3 on 2021-05-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corals',
            name='amount',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='corals',
            name='package',
            field=models.IntegerField(null=True, verbose_name='Package No.'),
        ),
        migrations.AddField(
            model_name='corals',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
