# Generated by Django 3.2.3 on 2021-05-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_auto_20210530_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='corals',
            name='set',
            field=models.CharField(max_length=100, null=True, verbose_name='Set'),
        ),
        migrations.AddField(
            model_name='corals',
            name='type',
            field=models.CharField(max_length=100, null=True, verbose_name='Type'),
        ),
    ]
